[package]
name = "win-clipboard"
version = "1.0.0"
authors = ["Sindre Sorhus <sindresorhus@gmail.com>", "Vsevolod Strukchinsky <floatdrop@gmail.com>"]

[dependencies]
clipboard-win = "2.0.1"
atty = { version = "0.2", optional = true }
